apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "multus.name" . }}-amd64
  labels: {{- include "multus.labels" .  | nindent 4}}
spec:
  selector:
    matchLabels: {{- include "multus.labels" .  | nindent 6}}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels: {{- include "multus.labels" .  | nindent 8}}
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: multus
      initContainers:
      - name: cni-installer
        image: {{ .Values.image.cni.repository -}}:{{- .Values.image.cni.tag }}
        volumeMounts:
        - name: cnibin
          mountPath: /opt/cni/bin    
      containers:
      - name: kube-multus
        image: {{ .Values.image.multus.repository -}}:{{- .Chart.AppVersion }}
        command: ["/entrypoint.sh"]
        args:
        - "--multus-conf-file=auto"
        - "--cni-version=0.3.1"
        {{- if contains "k3s" .Capabilities.KubeVersion.GitVersion }}
        - "--multus-kubeconfig-file-host=/var/lib/rancher/k3s/agent/etc/cni/net.d/multus.d/multus.kubeconfig"
        {{- end }}
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /host/opt/cni/bin
        - name: multus-cfg
          mountPath: /tmp/multus-conf
      volumes:
        - name: cni
          hostPath:
            {{- if contains "k3s" .Capabilities.KubeVersion.GitVersion }}
            path: /var/lib/rancher/k3s/agent/etc/cni/net.d
            {{- else }}
            path: /etc/cni/net.d
            {{- end }}
        - name: cnibin
          hostPath:
            {{- if contains "k3s" .Capabilities.KubeVersion.GitVersion }}
            path: /var/lib/rancher/k3s/data/current/bin
            {{- else }}
            path: /opt/cni/bin
            {{- end }}
        - name: multus-cfg
          configMap:
            name: {{ template "multus.name" . }}-config
            items:
            - key: cni-conf.json
              path: 70-multus.conf
